"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "vi" | "en" | "de";

export const dictionary: Record<Language, Record<string, string>> = {
  vi: {
    // Navigation & Common
    "app.title": "PronunCheck",
    "app.subtitle": "Luyện phát âm tiếng Đức thông minh",
    "language.vi": "Tiếng Việt",
    "language.en": "English",
    "language.de": "Deutsch",
    "common.loading": "Đang tải...",
    "common.processing": "Đang xử lý...",
    "common.cancel": "Hủy",
    "common.save": "Lưu thay đổi",
    "common.delete": "Xóa",
    "common.edit": "Sửa",
    "common.close": "Đóng",
    "common.confirm": "Xác nhận",
    "common.back": "Quay lại",
    "common.copy": "Sao chép",
    "common.copied": "Đã copy!",
    "common.or": "hoặc",
    "common.all": "Tất cả",
    "common.reset": "Đặt lại",
    "common.actions": "Thao tác",

    // Roles & Auth
    "role.student": "Học sinh",
    "role.teacher": "Giáo viên",
    "role.select_prompt": "Chọn vai trò của bạn",
    "role.student_desc": "Luyện tập phát âm, nộp bài tập và nhận phân tích AI tức thì.",
    "role.teacher_desc": "Tạo lớp học, giao bài tập và theo dõi tiến độ chi tiết của học sinh.",
    "auth.login": "Đăng nhập",
    "auth.register": "Đăng ký tài khoản",
    "auth.logout": "Đăng xuất",
    "auth.email": "Email",
    "auth.email_placeholder": "name@example.com",
    "auth.password": "Mật khẩu",
    "auth.password_placeholder": "Nhập mật khẩu (ít nhất 6 ký tự)",
    "auth.confirm_password": "Xác nhận mật khẩu",
    "auth.confirm_password_placeholder": "Nhập lại mật khẩu",
    "auth.forgot_password": "Quên mật khẩu?",
    "auth.forgot_password_desc": "Nhập email của bạn để nhận liên kết đặt lại mật khẩu.",
    "auth.send_reset_link": "Gửi email khôi phục",
    "auth.reset_sent": "Đã gửi email khôi phục! Vui lòng kiểm tra hòm thư.",
    "auth.show_password": "Hiện mật khẩu",
    "auth.hide_password": "Ẩn mật khẩu",
    "auth.dont_have_account": "Chưa có tài khoản? Đăng ký ngay",
    "auth.already_have_account": "Đã có tài khoản? Đăng nhập ngay",
    "auth.step1_role": "1. Chọn vai trò của bạn",
    "auth.step2_email": "2. Nhập địa chỉ Email",
    "auth.step3_password": "3. Thiết lập mật khẩu",
    "auth.step4_captcha": "4. Xác minh bảo mật (Chống Bot)",
    "auth.captcha_question": "Giải phép tính sau để xác minh:",
    "auth.captcha_placeholder": "Nhập kết quả...",
    "auth.captcha_error": "Kết quả xác minh không chính xác. Vui lòng thử lại.",
    "auth.password_mismatch": "Mật khẩu xác nhận không khớp.",
    "auth.password_too_short": "Mật khẩu cần ít nhất 6 ký tự.",
    "auth.invalid_email": "Địa chỉ email không đúng định dạng.",

    // Student Dashboard
    "student.dashboard": "Bảng điều khiển Học sinh",
    "student.free_practice": "Tự do luyện tập",
    "student.free_practice_desc": "Nhập từ hoặc câu tiếng Đức bất kỳ, ghi âm và nhận phân tích AI ngay.",
    "student.join_class": "Tham gia lớp học",
    "student.join_class_desc": "Nhập mã lớp và mật khẩu do giáo viên cung cấp để làm bài tập.",
    "student.my_classes": "Lớp học của tôi",
    "student.no_classes": "Bạn chưa tham gia lớp học nào. Hãy bấm 'Tham gia lớp học' để bắt đầu.",
    "student.class_id": "Mã lớp",
    "student.class_password": "Mật khẩu lớp",
    "student.class_password_placeholder": "Nhập mật khẩu lớp (nếu có)",
    "student.join_submit": "Tham gia lớp ngay",
    "student.join_success": "Tham gia lớp học thành công!",
    "student.class_not_found": "Không tìm thấy lớp học này.",
    "student.wrong_password": "Sai mật khẩu lớp học.",

    // Free Practice & Assignment Mode
    "practice.word_to_practice": "Từ hoặc câu muốn luyện tập",
    "practice.word_placeholder": "VD: Schule hoặc Guten Tag...",
    "practice.target_phoneme": "Âm mục tiêu",
    "practice.assignments_to_do": "Danh sách bài tập cần làm",
    "practice.no_assignments": "Lớp học chưa có bài tập nào.",
    "practice.attempts_left": "Còn lại",
    "practice.attempts": "lượt thử",
    "practice.deadline": "Hạn chót",
    "practice.no_deadline": "Không giới hạn",
    "practice.status_passed": "Đạt",
    "practice.status_failed": "Chưa đạt",
    "practice.status_pending": "Chưa làm",
    "practice.assignment_locked": "Bài tập này hiện đang tạm đóng.",
    "practice.deadline_passed": "Đã hết hạn nộp bài.",
    "practice.max_attempts_reached": "Bạn đã hết số lần nộp bài cho bài tập này.",
    "practice.completed_congrats": "Bạn đã hoàn thành xuất sắc bài tập này! 🎉",
    "practice.score_phonetics": "Âm vị",
    "practice.score_intonation": "Ngữ điệu",
    "practice.score_completeness": "Tính trọn vẹn",
    "practice.score_overall": "Tổng thể",
    "practice.score_precise": "Âm vị",
    "practice.score_whisper": "Tính trọn vẹn",
    "practice.score_total": "Tổng thể",
    "practice.try_again": "Thử lại",

    // Audio Recorder
    "recorder.start": "Bắt đầu ghi âm",
    "recorder.recording": "Đang ghi âm...",
    "recorder.stop": "Dừng ghi âm",
    "recorder.re_record": "Ghi âm lại",
    "recorder.upload_file": "Tải file lên",
    "recorder.submit_grade": "Chấm điểm ngay",
    "recorder.file_too_large": "File quá lớn. Vui lòng chọn file dưới 10MB.",
    "recorder.mic_permission_error": "Không thể truy cập Microphone. Vui lòng cấp quyền micro cho trình duyệt.",
    "recorder.enter_word_first": "Vui lòng nhập từ hoặc câu cần đọc trước khi ghi âm!",

    // Teacher Dashboard
    "teacher.dashboard": "Bảng điều khiển Giáo viên",
    "teacher.create_class": "Tạo lớp học mới",
    "teacher.class_name": "Tên lớp học",
    "teacher.class_name_placeholder": "VD: Tiếng Đức A1 - Khóa 2026",
    "teacher.class_password_optional": "Mật khẩu bảo vệ (tùy chọn)",
    "teacher.btn_create_class": "+ Tạo lớp học",
    "teacher.class_created": "Tạo lớp học thành công!",
    "teacher.my_classes": "Lớp học của bạn",
    "teacher.no_classes": "Bạn chưa tạo lớp học nào. Hãy tạo lớp học đầu tiên ở trên.",
    "teacher.delete_class_confirm": "Bạn có chắc muốn xóa lớp này? Toàn bộ bài tập và bài nộp sẽ bị mất vĩnh viễn.",
    "teacher.class_deleted": "Đã xóa lớp học thành công.",
    "teacher.has_password": "Có mật khẩu",
    "teacher.open_free": "Mở tự do",

    // Teacher Class Detail Tabs
    "tab.assignments": "Bài tập",
    "tab.scoring_config": "Cấu hình chấm điểm",
    "tab.submissions": "Kết quả học sinh",
    "tab.class_management": "Quản lý lớp học",

    // Analytics Dashboard
    "analytics.title": "Tổng quan Kết quả & Phân tích Nâng cao",
    "analytics.desc": "Thống kê phổ điểm, tỷ lệ vượt qua và đánh giá trung bình 3 kỹ năng phát âm của lớp.",
    "analytics.filter_assignment": "Chọn bài tập",
    "analytics.all_assignments": "📊 Tất cả bài tập trong lớp",
    "analytics.pass_rate": "Tỷ lệ Đạt",
    "analytics.avg_score": "Điểm trung bình",
    "analytics.active_students": "Học sinh tham gia",
    "analytics.students_count": "học sinh",
    "analytics.chart_score_dist": "Phân bổ Phổ Điểm Học Sinh",
    "analytics.chart_skills_avg": "Điểm Trung Bình 3 Kỹ Năng Cốt Lõi",
    "analytics.total_submissions": "Tổng bài nộp",
    "analytics.scale_100": "Thang điểm 0 - 100",
    "analytics.submissions_label": "bài nộp",
    "analytics.tier_excellent": "Xuất sắc (85+)",
    "analytics.tier_good": "Khá (70-84)",
    "analytics.tier_fair": "Trung bình (50-69)",
    "analytics.tier_poor": "Cần luyện (<50)",

    // Class Management
    "mgmt.export_title": "Xuất Báo Cáo Kết Quả Toàn Diện",
    "mgmt.export_desc": "Tải xuống file Excel (.xlsx) gồm 2 Sheet: Bảng tổng quan học sinh và chi tiết toàn bộ các lần nộp bài.",
    "mgmt.export_btn": "Tải Báo Cáo Excel",
    "mgmt.rename_class": "Đổi tên lớp học",
    "mgmt.rename_desc": "Cập nhật tên hiển thị của lớp học cho giáo viên và học sinh.",
    "mgmt.name_updated": "Đã đổi tên lớp học thành công!",
    "mgmt.password_title": "Mật khẩu bảo vệ lớp",
    "mgmt.password_desc": "Mật khẩu ngăn người lạ tham gia vào lớp. Để trống nếu muốn lớp học mở tự do.",
    "mgmt.class_password": "Mật khẩu tham gia lớp",
    "mgmt.clear_password": "Xóa mật khẩu (Mở tự do)",
    "mgmt.save_password": "Lưu mật khẩu",
    "mgmt.password_updated": "Đã cập nhật mật khẩu lớp học!",
    "mgmt.password_removed": "Đã chuyển lớp học sang chế độ Mở tự do!",
    "mgmt.members_title": "Danh sách Học sinh trong Lớp",
    "mgmt.members_count": "học sinh",
    "mgmt.members_desc": "Xem danh sách, tiến độ làm bài, thêm học sinh bằng email hoặc xóa khỏi lớp.",
    "mgmt.search_members": "Tìm học sinh theo email...",
    "mgmt.add_member_btn": "+ Thêm học sinh",
    "mgmt.member_added": "Đã thêm học sinh vào lớp học!",
    "mgmt.member_removed": "Đã xóa học sinh khỏi lớp học.",
    "mgmt.no_members": "Chưa có học sinh nào trong lớp. Hãy thêm bằng email ở trên hoặc chia sẻ Mã lớp.",
    "mgmt.no_search_match": "Không tìm thấy học sinh nào phù hợp.",
    "mgmt.th_joined": "Ngày tham gia",
    "mgmt.th_progress": "Số bài đã nộp",
    "mgmt.th_pass_rate": "Tỷ lệ Đạt",
    "mgmt.remove_member": "Xóa khỏi lớp",
    "mgmt.remove_confirm_title": "Xác nhận xóa học sinh khỏi lớp?",
    "mgmt.remove_confirm_desc": "Học sinh này sẽ bị xóa khỏi danh sách thành viên của lớp. Lịch sử các bài đã nộp trước đó vẫn được lưu trữ trong hệ thống.",
    "mgmt.excel_exported": "Đã tải file Excel báo cáo lớp học về máy!",
    
    // Assignment Form & Edit
    "assignment.create_title": "Tạo bài tập mới",
    "assignment.edit_title": "Chỉnh sửa bài tập",
    "assignment.name": "Tên bài tập",
    "assignment.name_placeholder": "VD: Bài 1 - Luyện đếm số từ 1 đến 10",
    "assignment.name_hint": "(Tùy chọn - Giúp hiển thị gọn gàng trong danh sách)",
    "assignment.word": "Từ / Câu cần đọc *",
    "assignment.word_placeholder": "VD: Schule hoặc eins zwei drei...",
    "assignment.phoneme": "Phoneme mục tiêu *",
    "assignment.phoneme_hint": "(nhập 'auto' nếu là câu dài)",
    "assignment.max_attempts": "Số lần thử tối đa",
    "assignment.deadline": "Hạn chót",
    "assignment.deadline_hint": "(để trống nếu không giới hạn)",
    "assignment.is_active": "Đang mở (Học sinh có thể nhìn thấy và làm bài)",
    "assignment.btn_create": "+ Tạo bài tập mới",
    "assignment.btn_save": "Lưu thay đổi",
    "assignment.created_success": "Tạo bài tập thành công!",
    "assignment.updated_success": "Cập nhật bài tập thành công!",
    "assignment.deleted_success": "Đã xóa bài tập thành công!",
    "assignment.delete_confirm_title": "Xác nhận xóa bài tập?",
    "assignment.delete_confirm_desc": "Thao tác này không thể hoàn tác. Học sinh sẽ không còn thấy bài tập này nữa.",
    "assignment.status_open": "● Đang mở",
    "assignment.status_closed": "○ Đã đóng",
    "assignment.toggle_open": "Mở lại",
    "assignment.toggle_close": "Đóng bài",

    // Scoring Config
    "config.title": "Cấu hình Chấm điểm AI (V3.5)",
    "config.desc": "Hệ thống sử dụng thuật toán Dynamic Sigmoid kết hợp Wav2Vec2, FastDTW và Faster-Whisper thích ứng theo độ dài câu.",
    "config.mode_auto": "🤖 Tự động (Khuyên dùng)",
    "config.mode_manual": "⚙️ Thủ công & Đồ thị SVG",
    "config.threshold": "Ngưỡng đạt bài tập (Passing Threshold)",
    "config.threshold_hint": "Học sinh đạt tổng điểm >= ngưỡng này sẽ được tính là Đạt.",
    "config.l0_label": "Điểm chuyển tiếp độ dài L0 (Trung tâm cân bằng âm vị / ngữ điệu)",
    "config.k_label": "Độ dốc chuyển đổi k (Tốc độ chuyển giao trọng số)",
    "config.graph_title": "Đồ thị Phân bổ Trọng số Động theo Độ dài Hiệu dụng L",
    "config.graph_desc": "Đường màu xanh (Âm vị) giảm dần, đường màu tím (Ngữ điệu) tăng dần khi câu dài ra. Đường nằm ngang màu vàng là Ngưỡng Đạt.",
    "config.sim_title": "Thử nghiệm Mô phỏng Trọng số Nhanh:",
    "config.sim_short": "🔤 Từ ngắn (L≈1.5): Schule",
    "config.sim_medium": "📑 Cụm từ (L≈4.5): das Mineralwasser",
    "config.sim_long": "📖 Câu dài (L≈8.0): Ich lerne heute Deutsch",
    "config.save_btn": "Lưu cấu hình",
    "config.saved_success": "Lưu cấu hình thành công!",

    // Submissions Table & Filters
    "sub.title": "Kết quả học sinh",
    "sub.submissions_count": "bài nộp",
    "sub.filter_by": "Đang lọc theo:",
    "sub.filter_email": "Email học sinh",
    "sub.filter_assignment": "Bài tập / Từ đọc",
    "sub.filter_result": "Kết quả",
    "sub.search_email": "Tìm email...",
    "sub.search_assignment": "Tìm bài tập...",
    "sub.select_all": "Chọn tất cả",
    "sub.deselect_all": "Bỏ chọn",
    "sub.th_email": "Email học sinh",
    "sub.th_word": "Bài tập / Từ đọc",
    "sub.th_time": "Thời gian nộp",
    "sub.th_attempt": "Lần thử",
    "sub.th_phoneme": "Âm vị",
    "sub.th_intonation": "Ngữ điệu",
    "sub.th_whisper": "Tính trọn vẹn",
    "sub.th_total": "Tổng thể",
    "sub.th_result": "Kết quả",
    "sub.th_listen": "Nghe",
    "sub.th_manage": "Quản lý",
    "sub.add_note": "Thêm / Sửa Ghi chú",
    "sub.delete_sub": "Xóa lượt nộp này",
    "sub.teacher_note": "Ghi chú của giáo viên",
    "sub.note_modal_title": "Ghi chú cho Lượt Làm Bài này",
    "sub.note_placeholder": "Nhập nhận xét hoặc lời khuyên cho học sinh (học sinh sẽ nhìn thấy khi xem lịch sử)...",
    "sub.note_saved": "Đã lưu ghi chú thành công!",
    "sub.delete_confirm_title": "Xác nhận xóa lượt nộp này?",
    "sub.delete_confirm_desc": "Thao tác này không thể hoàn tác. Điểm số và file ghi âm của lượt này sẽ bị xóa khỏi hệ thống.",
    "sub.sub_deleted": "Đã xóa bài nộp thành công!",
    "sub.expand_details": "Xem chi tiết Karaoke",
    "sub.collapse_details": "Thu gọn",
    "assignment.delete_with_subs": "Xóa bài tập & Toàn bộ kết quả",
    "assignment.delete_only_assign": "Chỉ xóa bài tập (Giữ lại kết quả)",
    "practice.teacher_note_title": "Lời nhắn từ giáo viên",
    "sub.no_submissions": "Chưa có bài nộp nào.",
    "sub.no_filter_match": "Không tìm thấy bài nộp nào phù hợp với bộ lọc hiện tại.",
    "sub.play_error": "Không thể phát file ghi âm này.",

    // PWA
    "pwa.install_title": "Cài đặt PronunCheck",
    "pwa.install_desc": "Thêm vào màn hình chính để luyện phát âm mượt mà như app chuyên dụng.",
    "pwa.install_btn": "Cài đặt ngay",
    "pwa.how_to_install": "Hướng dẫn cài đặt",
    "pwa.ios_guide_title": "Cài đặt ứng dụng trên Safari iOS",
    "pwa.ios_guide_desc": "Để cài đặt PronunCheck lên màn hình chính iPhone/iPad, bạn làm theo 3 bước sau:",
    "pwa.ios_step1": "Nhấn vào nút Chia sẻ ở thanh công cụ dưới cùng Safari",
    "pwa.ios_step2": "Cuộn xuống và chọn \"Thêm vào MH chính\" (Add to Home Screen)",
    "pwa.ios_step3": "Nhấn \"Thêm\" (Add) ở góc trên bên phải để hoàn tất",
    "pwa.dismiss": "Để sau",
    "pwa.close": "Đóng",
  },

  en: {
    // Navigation & Common
    "app.title": "PronunCheck",
    "app.subtitle": "Smart German Pronunciation Practice",
    "language.vi": "Tiếng Việt",
    "language.en": "English",
    "language.de": "Deutsch",
    "common.loading": "Loading...",
    "common.processing": "Processing...",
    "common.cancel": "Cancel",
    "common.save": "Save Changes",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.back": "Go Back",
    "common.copy": "Copy",
    "common.copied": "Copied!",
    "common.or": "or",
    "common.all": "All",
    "common.reset": "Reset",
    "common.actions": "Actions",

    // Roles & Auth
    "role.student": "Student",
    "role.teacher": "Teacher",
    "role.select_prompt": "Select your role",
    "role.student_desc": "Practice pronunciation, submit assignments and get instant AI feedback.",
    "role.teacher_desc": "Create classrooms, assign exercises and track detailed student progress.",
    "auth.login": "Sign In",
    "auth.register": "Create Account",
    "auth.logout": "Sign Out",
    "auth.email": "Email Address",
    "auth.email_placeholder": "name@example.com",
    "auth.password": "Password",
    "auth.password_placeholder": "Enter password (at least 6 chars)",
    "auth.confirm_password": "Confirm Password",
    "auth.confirm_password_placeholder": "Re-enter password",
    "auth.forgot_password": "Forgot Password?",
    "auth.forgot_password_desc": "Enter your email to receive a password reset link.",
    "auth.send_reset_link": "Send Reset Link",
    "auth.reset_sent": "Reset email sent! Please check your inbox.",
    "auth.show_password": "Show password",
    "auth.hide_password": "Hide password",
    "auth.dont_have_account": "Don't have an account? Sign up now",
    "auth.already_have_account": "Already have an account? Sign in now",
    "auth.step1_role": "1. Select your role",
    "auth.step2_email": "2. Enter your Email",
    "auth.step3_password": "3. Set your Password",
    "auth.step4_captcha": "4. Security Verification (Bot Protection)",
    "auth.captcha_question": "Solve this equation to verify:",
    "auth.captcha_placeholder": "Enter answer...",
    "auth.captcha_error": "Verification answer is incorrect. Please try again.",
    "auth.password_mismatch": "Passwords do not match.",
    "auth.password_too_short": "Password must be at least 6 characters.",
    "auth.invalid_email": "Invalid email address format.",

    // Student Dashboard
    "student.dashboard": "Student Dashboard",
    "student.free_practice": "Free Practice",
    "student.free_practice_desc": "Type any German word or sentence, record audio and receive instant AI grading.",
    "student.join_class": "Join a Class",
    "student.join_class_desc": "Enter Class ID and password provided by your teacher to do exercises.",
    "student.my_classes": "My Classrooms",
    "student.no_classes": "You haven't joined any classes yet. Click 'Join a Class' to begin.",
    "student.class_id": "Class ID",
    "student.class_password": "Class Password",
    "student.class_password_placeholder": "Enter class password (if any)",
    "student.join_submit": "Join Classroom",
    "student.join_success": "Successfully joined classroom!",
    "student.class_not_found": "Classroom not found.",
    "student.wrong_password": "Incorrect class password.",

    // Free Practice & Assignment Mode
    "practice.word_to_practice": "Word or sentence to practice",
    "practice.word_placeholder": "E.g. Schule or Guten Tag...",
    "practice.target_phoneme": "Target Phoneme",
    "practice.assignments_to_do": "Assigned Exercises",
    "practice.no_assignments": "No exercises in this class yet.",
    "practice.attempts_left": "Remaining",
    "practice.attempts": "attempts",
    "practice.deadline": "Deadline",
    "practice.no_deadline": "No deadline",
    "practice.status_passed": "Passed",
    "practice.status_failed": "Needs Work",
    "practice.status_pending": "Not started",
    "practice.assignment_locked": "This assignment is currently closed.",
    "practice.deadline_passed": "Deadline has passed.",
    "practice.max_attempts_reached": "You have used all attempts for this assignment.",
    "practice.completed_congrats": "You have successfully passed this assignment! 🎉",
    "practice.score_phonetics": "Phonetics",
    "practice.score_intonation": "Intonation",
    "practice.score_completeness": "Completeness",
    "practice.score_overall": "Overall",
    "practice.score_precise": "Phonetics",
    "practice.score_whisper": "Completeness",
    "practice.score_total": "Overall",
    "practice.try_again": "Try Again",

    // Audio Recorder
    "recorder.start": "Start Recording",
    "recorder.recording": "Recording...",
    "recorder.stop": "Stop Recording",
    "recorder.re_record": "Re-record",
    "recorder.upload_file": "Upload Audio",
    "recorder.submit_grade": "Grade My Voice",
    "recorder.file_too_large": "File is too large. Please upload files under 10MB.",
    "recorder.mic_permission_error": "Cannot access microphone. Please grant mic permission in your browser.",
    "recorder.enter_word_first": "Please enter target word/sentence before recording!",

    // Teacher Dashboard
    "teacher.dashboard": "Teacher Dashboard",
    "teacher.create_class": "Create New Classroom",
    "teacher.class_name": "Class Name",
    "teacher.class_name_placeholder": "E.g. German A1 - Fall 2026",
    "teacher.class_password_optional": "Protection password (optional)",
    "teacher.btn_create_class": "+ Create Class",
    "teacher.class_created": "Classroom created successfully!",
    "teacher.my_classes": "Your Classrooms",
    "teacher.no_classes": "You have not created any classes yet.",
    "teacher.delete_class_confirm": "Are you sure you want to delete this class? All assignments and submissions will be permanently lost.",
    "teacher.class_deleted": "Classroom deleted successfully.",
    "teacher.has_password": "Password protected",
    "teacher.open_free": "Open access",

    // Teacher Class Detail Tabs
    "tab.assignments": "Assignments",
    "tab.scoring_config": "Scoring Config",
    "tab.submissions": "Student Results",
    "tab.class_management": "Class Management",

    // Analytics Dashboard
    "analytics.title": "Results Overview & Advanced Analytics",
    "analytics.desc": "Score distribution, pass rates, and average pronunciation skill metrics.",
    "analytics.filter_assignment": "Filter by Assignment",
    "analytics.all_assignments": "📊 All Class Assignments",
    "analytics.pass_rate": "Pass Rate",
    "analytics.avg_score": "Average Score",
    "analytics.active_students": "Active Students",
    "analytics.students_count": "students",
    "analytics.chart_score_dist": "Student Score Distribution",
    "analytics.chart_skills_avg": "Core Skills Average Breakdown",
    "analytics.total_submissions": "Total submissions",
    "analytics.scale_100": "Scale 0 - 100",
    "analytics.submissions_label": "submissions",
    "analytics.tier_excellent": "Excellent (85+)",
    "analytics.tier_good": "Good (70-84)",
    "analytics.tier_fair": "Fair (50-69)",
    "analytics.tier_poor": "Needs Work (<50)",

    // Class Management
    "mgmt.export_title": "Export Comprehensive Class Report",
    "mgmt.export_desc": "Download Excel (.xlsx) with 2 sheets: Student Overview and Full Submissions Log.",
    "mgmt.export_btn": "Download Excel Report",
    "mgmt.rename_class": "Rename Classroom",
    "mgmt.rename_desc": "Update classroom display name for teacher and students.",
    "mgmt.name_updated": "Classroom renamed successfully!",
    "mgmt.password_title": "Classroom Protection Password",
    "mgmt.password_desc": "Password prevents unauthorized students. Leave empty for open access.",
    "mgmt.class_password": "Join Password",
    "mgmt.clear_password": "Remove Password (Open Access)",
    "mgmt.save_password": "Save Password",
    "mgmt.password_updated": "Classroom password updated!",
    "mgmt.password_removed": "Classroom changed to open access!",
    "mgmt.members_title": "Classroom Student Roster",
    "mgmt.members_count": "students",
    "mgmt.members_desc": "View roster, student progress, add by email or remove members.",
    "mgmt.search_members": "Search student by email...",
    "mgmt.add_member_btn": "+ Add Student",
    "mgmt.member_added": "Student added to class!",
    "mgmt.member_removed": "Student removed from class.",
    "mgmt.no_members": "No students in this class yet. Add via email or share the Class ID.",
    "mgmt.no_search_match": "No matching students found.",
    "mgmt.th_joined": "Joined Date",
    "mgmt.th_progress": "Submissions",
    "mgmt.th_pass_rate": "Pass Rate",
    "mgmt.remove_member": "Remove student",
    "mgmt.remove_confirm_title": "Remove student from classroom?",
    "mgmt.remove_confirm_desc": "This student will be removed from the class roster. Prior submission history remains archived.",
    "mgmt.excel_exported": "Excel report downloaded successfully!",
    
    // Assignment Form & Edit
    "assignment.create_title": "Create New Assignment",
    "assignment.edit_title": "Edit Assignment",
    "assignment.name": "Assignment Title",
    "assignment.name_placeholder": "E.g. Lesson 1 - Count from 1 to 10",
    "assignment.name_hint": "(Optional - keeps exercise list tidy)",
    "assignment.word": "Target Word / Sentence *",
    "assignment.word_placeholder": "E.g. Schule or eins zwei drei...",
    "assignment.phoneme": "Target Phoneme *",
    "assignment.phoneme_hint": "(enter 'auto' for long sentences)",
    "assignment.max_attempts": "Max Attempts",
    "assignment.deadline": "Deadline",
    "assignment.deadline_hint": "(leave empty for no limit)",
    "assignment.is_active": "Open (Students can view and practice)",
    "assignment.btn_create": "+ Create Assignment",
    "assignment.btn_save": "Save Changes",
    "assignment.created_success": "Assignment created successfully!",
    "assignment.updated_success": "Assignment updated successfully!",
    "assignment.deleted_success": "Assignment deleted successfully!",
    "assignment.delete_confirm_title": "Delete this assignment?",
    "assignment.delete_confirm_desc": "This action cannot be undone. Students will no longer see this assignment.",
    "assignment.status_open": "● Open",
    "assignment.status_closed": "○ Closed",
    "assignment.toggle_open": "Reopen",
    "assignment.toggle_close": "Close",

    // Scoring Config
    "config.title": "AI Scoring Engine (V3.5)",
    "config.desc": "Combines Wav2Vec2 German phonetics, FastDTW pitch intonation and Faster-Whisper dynamically adapting to sentence length.",
    "config.mode_auto": "🤖 Automatic (Recommended)",
    "config.mode_manual": "⚙️ Manual & Interactive Graph",
    "config.threshold": "Passing Threshold",
    "config.threshold_hint": "Students with overall score >= threshold will be marked as Passed.",
    "config.l0_label": "Crossover Length Threshold L0 (Balance center between phoneme & intonation)",
    "config.k_label": "Sigmoid Transition Slope k (Weight transfer rate)",
    "config.graph_title": "Dynamic Weight Distribution vs Effective Length (L)",
    "config.graph_desc": "Green curve (Phoneme) decreases, Purple curve (Intonation/Fluency) increases as sentence length grows. Dashed yellow line is Passing Threshold.",
    "config.sim_title": "Quick Live Simulation Sandbox:",
    "config.sim_short": "🔤 Short Word (L≈1.5): Schule",
    "config.sim_medium": "📑 Phrase (L≈4.5): das Mineralwasser",
    "config.sim_long": "📖 Long Sentence (L≈8.0): Ich lerne heute Deutsch",
    "config.save_btn": "Save Config",
    "config.saved_success": "Scoring config saved successfully!",

    // Submissions Table & Filters
    "sub.title": "Student Submissions",
    "sub.submissions_count": "submissions",
    "sub.filter_by": "Active filters:",
    "sub.filter_email": "Student Email",
    "sub.filter_assignment": "Assignment / Text",
    "sub.filter_result": "Result",
    "sub.search_email": "Search email...",
    "sub.search_assignment": "Search assignment...",
    "sub.select_all": "Select All",
    "sub.deselect_all": "Deselect",
    "sub.th_email": "Student Email",
    "sub.th_word": "Assignment / Text",
    "sub.th_time": "Submitted At",
    "sub.th_attempt": "Attempt",
    "sub.th_phoneme": "Phonetics",
    "sub.th_intonation": "Intonation",
    "sub.th_whisper": "Completeness",
    "sub.th_result": "Result",
    "sub.th_listen": "Listen",
    "sub.th_manage": "Manage",
    "sub.add_note": "Add / Edit Note",
    "sub.delete_sub": "Delete Submission",
    "sub.teacher_note": "Teacher Note",
    "sub.note_modal_title": "Teacher Note for Submission",
    "sub.note_placeholder": "Enter feedback, phonetic guidance, or tips for this student...",
    "sub.note_saved": "Teacher note saved successfully!",
    "sub.delete_confirm_title": "Delete this student submission?",
    "sub.delete_confirm_desc": "This action cannot be undone. The student's scores and recording will be permanently deleted.",
    "sub.sub_deleted": "Submission deleted successfully!",
    "sub.expand_details": "Expand Karaoke Details",
    "sub.collapse_details": "Collapse",
    "assignment.delete_with_subs": "Delete Assignment & All Submissions",
    "assignment.delete_only_assign": "Only Delete Assignment (Keep Results)",
    "practice.teacher_note_title": "Teacher Note",
    "sub.no_submissions": "No submissions in this class yet.",
    "sub.no_filter_match": "No submissions match current filters.",
    "sub.play_error": "Cannot play this audio recording.",

    // PWA
    "pwa.install_title": "Install PronunCheck",
    "pwa.install_desc": "Add to home screen for a fast, native app pronunciation practice experience.",
    "pwa.install_btn": "Install Now",
    "pwa.how_to_install": "Install Guide",
    "pwa.ios_guide_title": "Install App on Safari iOS",
    "pwa.ios_guide_desc": "To add PronunCheck to your iPhone/iPad Home Screen, follow these 3 steps:",
    "pwa.ios_step1": "Tap the Share button on the bottom bar of Safari",
    "pwa.ios_step2": "Scroll down and select \"Add to Home Screen\"",
    "pwa.ios_step3": "Tap \"Add\" in the top right corner",
    "pwa.dismiss": "Not now",
    "pwa.close": "Close",
  },

  de: {
    // Navigation & Common
    "app.title": "PronunCheck",
    "app.subtitle": "Intelligentes deutsches Aussprachetraining",
    "language.vi": "Tiếng Việt",
    "language.en": "English",
    "language.de": "Deutsch",
    "common.loading": "Wird geladen...",
    "common.processing": "Bitte warten...",
    "common.cancel": "Abbrechen",
    "common.save": "Änderungen speichern",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.close": "Schließen",
    "common.confirm": "Bestätigen",
    "common.back": "Zurück",
    "common.copy": "Kopieren",
    "common.copied": "Kopiert!",
    "common.or": "oder",
    "common.all": "Alle",
    "common.reset": "Zurücksetzen",
    "common.actions": "Aktionen",

    // Roles & Auth
    "role.student": "Schüler",
    "role.teacher": "Lehrer",
    "role.select_prompt": "Wählen Sie Ihre Rolle",
    "role.student_desc": "Aussprache üben, Aufgaben abgeben und sofortiges KI-Feedback erhalten.",
    "role.teacher_desc": "Klassen erstellen, Aufgaben zuweisen und den Lernfortschritt verfolgen.",
    "auth.login": "Anmelden",
    "auth.register": "Konto erstellen",
    "auth.logout": "Abmelden",
    "auth.email": "E-Mail-Adresse",
    "auth.email_placeholder": "name@beispiel.de",
    "auth.password": "Passwort",
    "auth.password_placeholder": "Passwort eingeben (mind. 6 Zeichen)",
    "auth.confirm_password": "Passwort bestätigen",
    "auth.confirm_password_placeholder": "Passwort wiederholen",
    "auth.forgot_password": "Passwort vergessen?",
    "auth.forgot_password_desc": "Geben Sie Ihre E-Mail ein, um einen Link zum Zurücksetzen zu erhalten.",
    "auth.send_reset_link": "Link senden",
    "auth.reset_sent": "Link gesendet! Bitte überprüfen Sie Ihren Posteingang.",
    "auth.show_password": "Passwort anzeigen",
    "auth.hide_password": "Passwort verbergen",
    "auth.dont_have_account": "Noch kein Konto? Jetzt registrieren",
    "auth.already_have_account": "Bereits registriert? Jetzt anmelden",
    "auth.step1_role": "1. Wählen Sie Ihre Rolle",
    "auth.step2_email": "2. E-Mail-Adresse eingeben",
    "auth.step3_password": "3. Passwort festlegen",
    "auth.step4_captcha": "4. Sicherheitsüberprüfung (Bot-Schutz)",
    "auth.captcha_question": "Lösen Sie diese Aufgabe zur Bestätigung:",
    "auth.captcha_placeholder": "Ergebnis eingeben...",
    "auth.captcha_error": "Das Ergebnis ist falsch. Bitte versuchen Sie es erneut.",
    "auth.password_mismatch": "Passwörter stimmen nicht überein.",
    "auth.password_too_short": "Passwort muss mindestens 6 Zeichen lang sein.",
    "auth.invalid_email": "Ungültiges E-Mail-Format.",

    // Student Dashboard
    "student.dashboard": "Schüler-Dashboard",
    "student.free_practice": "Freies Üben",
    "student.free_practice_desc": "Geben Sie ein beliebiges deutsches Wort ein und erhalten Sie sofort KI-Feedback.",
    "student.join_class": "Kurs beitreten",
    "student.join_class_desc": "Kurs-ID und Passwort eingeben, um Aufgaben zu bearbeiten.",
    "student.my_classes": "Meine Kurse",
    "student.no_classes": "Sie sind noch keinem Kurs beigetreten.",
    "student.class_id": "Kurs-ID",
    "student.class_password": "Kurspasswort",
    "student.class_password_placeholder": "Kurspasswort eingeben (falls vorhanden)",
    "student.join_submit": "Jetzt beitreten",
    "student.join_success": "Erfolgreich dem Kurs beigetreten!",
    "student.class_not_found": "Kurs nicht gefunden.",
    "student.wrong_password": "Falsches Kurspasswort.",

    // Free Practice & Assignment Mode
    "practice.word_to_practice": "Zu übendes Wort / Satz",
    "practice.word_placeholder": "Z.B. Schule oder Guten Tag...",
    "practice.target_phoneme": "Ziel-Phonem",
    "practice.assignments_to_do": "Aufgabenliste",
    "practice.no_assignments": "In diesem Kurs gibt es noch keine Aufgaben.",
    "practice.attempts_left": "Verbleibend",
    "practice.attempts": "Versuche",
    "practice.deadline": "Frist",
    "practice.no_deadline": "Keine Frist",
    "practice.status_passed": "Bestanden",
    "practice.status_failed": "Nicht bestanden",
    "practice.status_pending": "Offen",
    "practice.assignment_locked": "Diese Aufgabe ist momentan geschlossen.",
    "practice.deadline_passed": "Die Abgabefrist ist abgelaufen.",
    "practice.max_attempts_reached": "Sie haben alle Versuche für diese Aufgabe aufgebraucht.",
    "practice.completed_congrats": "Sie haben diese Aufgabe erfolgreich abgeschlossen! 🎉",
    "practice.score_precise": "Phonem-Genauigkeit",
    "practice.score_intonation": "Intonation (F0 DTW)",
    "practice.score_whisper": "Vollständigkeit",
    "practice.score_total": "Gesamtergebnis",
    "practice.try_again": "Erneut versuchen",

    // Audio Recorder
    "recorder.start": "Aufnahme starten",
    "recorder.recording": "Aufnahme läuft...",
    "recorder.stop": "Aufnahme stoppen",
    "recorder.re_record": "Erneut aufnehmen",
    "recorder.upload_file": "Audiodatei hochladen",
    "recorder.submit_grade": "Jetzt bewerten",
    "recorder.file_too_large": "Datei zu groß. Bitte Dateien unter 10MB wählen.",
    "recorder.mic_permission_error": "Kein Zugriff auf das Mikrofon. Bitte Berechtigung im Browser erteilen.",
    "recorder.enter_word_first": "Bitte vor der Aufnahme das Zielwort eingeben!",

    // Teacher Dashboard
    "teacher.dashboard": "Lehrer-Dashboard",
    "teacher.create_class": "Neuen Kurs erstellen",
    "teacher.class_name": "Kursname",
    "teacher.class_name_placeholder": "Z.B. Deutsch A1 - Herbst 2026",
    "teacher.class_password_optional": "Passwortschutz (optional)",
    "teacher.btn_create_class": "+ Kurs erstellen",
    "teacher.class_created": "Kurs erfolgreich erstellt!",
    "teacher.my_classes": "Ihre Kurse",
    "teacher.no_classes": "Sie haben noch keine Kurse erstellt.",
    "teacher.delete_class_confirm": "Möchten Sie diesen Kurs wirklich löschen? Alle Aufgaben und Abgaben gehen unwiderruflich verloren.",
    "teacher.class_deleted": "Kurs erfolgreich gelöscht.",
    "teacher.has_password": "Passwortgeschützt",
    "teacher.open_free": "Frei zugänglich",

    // Teacher Class Detail Tabs
    "tab.assignments": "Aufgaben",
    "tab.scoring_config": "Bewertungskonfiguration",
    "tab.submissions": "Schülerergebnisse",
    "tab.class_management": "Klassenverwaltung",

    // Analytics Dashboard
    "analytics.title": "Ergebnisübersicht & Erweiterte Analysen",
    "analytics.desc": "Punkteverteilung, Bestehensquoten und durchschnittliche Aussprachemetriken.",
    "analytics.filter_assignment": "Nach Aufgabe filtern",
    "analytics.all_assignments": "📊 Alle Kursaufgaben",
    "analytics.pass_rate": "Bestehensquote",
    "analytics.avg_score": "Durchschnittspunktzahl",
    "analytics.active_students": "Aktive Schüler",
    "analytics.students_count": "Schüler",
    "analytics.chart_score_dist": "Punkteverteilung der Schüler",
    "analytics.chart_skills_avg": "Durchschnitt der Kernkompetenzen",
    "analytics.total_submissions": "Gesamtabgaben",
    "analytics.scale_100": "Skala 0 - 100",
    "analytics.submissions_label": "Abgaben",
    "analytics.tier_excellent": "Ausgezeichnet (85+)",
    "analytics.tier_good": "Gut (70-84)",
    "analytics.tier_fair": "Befriedigend (50-69)",
    "analytics.tier_poor": "Übungsbedarf (<50)",

    // Class Management
    "mgmt.export_title": "Umfassenden Kursbericht exportieren",
    "mgmt.export_desc": "Excel (.xlsx) mit 2 Tabellen herunterladen: Schülerübersicht und vollständiges Abgabeprotokoll.",
    "mgmt.export_btn": "Excel-Bericht herunterladen",
    "mgmt.rename_class": "Kurs umbenennen",
    "mgmt.rename_desc": "Anzeigenamen des Kurses für Lehrer und Schüler aktualisieren.",
    "mgmt.name_updated": "Kurs erfolgreich umbenannt!",
    "mgmt.password_title": "Kursschutz-Passwort",
    "mgmt.password_desc": "Verhindert unbefugten Zugriff. Leer lassen für freien Zugang.",
    "mgmt.class_password": "Beitrittspasswort",
    "mgmt.clear_password": "Passwort entfernen (Freier Zugang)",
    "mgmt.save_password": "Passwort speichern",
    "mgmt.password_updated": "Kurspasswort aktualisiert!",
    "mgmt.password_removed": "Kurs auf freien Zugang umgestellt!",
    "mgmt.members_title": "Schülerliste des Kurses",
    "mgmt.members_count": "Schüler",
    "mgmt.members_desc": "Liste und Fortschritt ansehen, per E-Mail hinzufügen oder entfernen.",
    "mgmt.search_members": "Schüler nach E-Mail suchen...",
    "mgmt.add_member_btn": "+ Schüler hinzufügen",
    "mgmt.member_added": "Schüler zum Kurs hinzugefügt!",
    "mgmt.member_removed": "Schüler aus dem Kurs entfernt.",
    "mgmt.no_members": "Noch keine Schüler in diesem Kurs. Per E-Mail hinzufügen oder Kurs-ID teilen.",
    "mgmt.no_search_match": "Keine passenden Schüler gefunden.",
    "mgmt.th_joined": "Beitrittsdatum",
    "mgmt.th_progress": "Abgaben",
    "mgmt.th_pass_rate": "Bestehensquote",
    "mgmt.remove_member": "Aus Kurs entfernen",
    "mgmt.remove_confirm_title": "Schüler wirklich entfernen?",
    "mgmt.remove_confirm_desc": "Dieser Schüler wird aus der Kursliste entfernt. Bisherige Abgaben bleiben archiviert.",
    "mgmt.excel_exported": "Excel-Bericht erfolgreich heruntergeladen!",
    
    // Assignment Form & Edit
    "assignment.create_title": "Neue Aufgabe erstellen",
    "assignment.edit_title": "Aufgabe bearbeiten",
    "assignment.name": "Aufgabentitel",
    "assignment.name_placeholder": "Z.B. Lektion 1 - Zählen von 1 bis 10",
    "assignment.name_hint": "(Optional - für übersichtliche Listen)",
    "assignment.word": "Zu sprechendes Wort / Satz *",
    "assignment.word_placeholder": "Z.B. Schule oder eins zwei drei...",
    "assignment.phoneme": "Ziel-Phonem *",
    "assignment.phoneme_hint": "('auto' für ganze Sätze eingeben)",
    "assignment.max_attempts": "Maximale Versuche",
    "assignment.deadline": "Frist",
    "assignment.deadline_hint": "(leer lassen für unbegrenzt)",
    "assignment.is_active": "Aktiv (Schüler können die Aufgabe sehen und üben)",
    "assignment.btn_create": "+ Aufgabe erstellen",
    "assignment.btn_save": "Speichern",
    "assignment.created_success": "Aufgabe erfolgreich erstellt!",
    "assignment.updated_success": "Aufgabe erfolgreich aktualisiert!",
    "assignment.deleted_success": "Aufgabe erfolgreich gelöscht!",
    "assignment.delete_confirm_title": "Aufgabe löschen?",
    "assignment.delete_confirm_desc": "Dies kann nicht rückgängig gemacht werden.",
    "assignment.status_open": "● Geöffnet",
    "assignment.status_closed": "○ Geschlossen",
    "assignment.toggle_open": "Öffnen",
    "assignment.toggle_close": "Schließen",

    // Scoring Config
    "config.title": "KI-Bewertungs-Engine (V3.5)",
    "config.desc": "Kombination aus Wav2Vec2, FastDTW-Intonation und Faster-Whisper, dynamisch an Satzlänge angepasst.",
    "config.mode_auto": "🤖 Automatisch (Empfohlen)",
    "config.mode_manual": "⚙️ Manuell & Interaktiver Graph",
    "config.threshold": "Bestehensgrenze (Passing Threshold)",
    "config.threshold_hint": "Schüler mit einer Gesamtnote >= dieser Grenze haben bestanden.",
    "config.l0_label": "Übergangsschwelle L0 (Gleichgewichtszentrum Phonetik / Intonation)",
    "config.k_label": "Sigmoid-Steigung k (Gewichtsübergangsrate)",
    "config.graph_title": "Dynamische Gewichtsverteilung nach effektiver Länge (L)",
    "config.graph_desc": "Grüne Kurve (Phonetik) sinkt, violette Kurve (Intonation) steigt mit längeren Sätzen. Gestrichelte gelbe Linie ist Bestehensgrenze.",
    "config.sim_title": "Schnelle Live-Simulation:",
    "config.sim_short": "🔤 Kurzwort (L≈1.5): Schule",
    "config.sim_medium": "📑 Phrase (L≈4.5): das Mineralwasser",
    "config.sim_long": "📖 Langer Satz (L≈8.0): Ich lerne heute Deutsch",
    "config.save_btn": "Konfiguration speichern",
    "config.saved_success": "Konfiguration erfolgreich gespeichert!",

    // Submissions Table & Filters
    "sub.title": "Schülerergebnisse",
    "sub.submissions_count": "Abgaben",
    "sub.filter_by": "Aktive Filter:",
    "sub.filter_email": "Schüler-E-Mail",
    "sub.filter_assignment": "Aufgabe / Text",
    "sub.filter_result": "Ergebnis",
    "sub.search_email": "E-Mail suchen...",
    "sub.search_assignment": "Aufgabe suchen...",
    "sub.select_all": "Alle auswählen",
    "sub.deselect_all": "Auswahl aufheben",
    "sub.th_email": "Schüler-E-Mail",
    "sub.th_word": "Aufgabe / Text",
    "sub.th_attempt": "Versuch",
    "sub.th_phoneme": "Phonem",
    "sub.th_intonation": "Intonation",
    "sub.th_whisper": "Whisper",
    "sub.th_total": "Gesamt",
    "sub.th_result": "Ergebnis",
    "sub.th_listen": "Anhören",
    "sub.th_manage": "Verwalten",
    "sub.add_note": "Notiz hinzufügen/bearbeiten",
    "sub.delete_sub": "Abgabe löschen",
    "sub.teacher_note": "Lehrernotiz",
    "sub.note_modal_title": "Lehrernotiz für diese Abgabe",
    "sub.note_placeholder": "Feedback oder Hinweise für den Schüler eingeben...",
    "sub.note_saved": "Notiz erfolgreich gespeichert!",
    "sub.delete_confirm_title": "Diese Abgabe löschen?",
    "sub.delete_confirm_desc": "Diese Aktion kann nicht rückgängig gemacht werden. Aufnahme und Ergebnisse werden gelöscht.",
    "sub.sub_deleted": "Abgabe erfolgreich gelöscht!",
    "sub.expand_details": "Karaoke-Details anzeigen",
    "sub.collapse_details": "Einklappen",
    "assignment.delete_with_subs": "Aufgabe & alle Abgaben löschen",
    "assignment.delete_only_assign": "Nur Aufgabe löschen (Ergebnisse behalten)",
    "practice.teacher_note_title": "Hinweis vom Lehrer",
    "sub.no_submissions": "Noch keine Abgaben in diesem Kurs.",
    "sub.no_filter_match": "Keine Abgaben entsprechen den Filtern.",
    "sub.play_error": "Audiodatei kann nicht abgespielt werden.",

    // PWA
    "pwa.install_title": "PronunCheck installieren",
    "pwa.install_desc": "Zum Startbildschirm hinzufügen für ein schnelles App-Erlebnis.",
    "pwa.install_btn": "Jetzt installieren",
    "pwa.how_to_install": "Installationsanleitung",
    "pwa.ios_guide_title": "App auf Safari iOS installieren",
    "pwa.ios_guide_desc": "Um PronunCheck zu Ihrem iPhone/iPad hinzuzufügen, befolgen Sie diese 3 Schritte:",
    "pwa.ios_step1": "Tippen Sie in Safari auf die Schaltfläche 'Teilen'",
    "pwa.ios_step2": "Scrollen Sie nach unten und wählen Sie 'Zum Home-Bildschirm'",
    "pwa.ios_step3": "Tippen Sie oben rechts auf 'Hinzufügen'",
    "pwa.dismiss": "Später",
    "pwa.close": "Schließen",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const savedLang = localStorage.getItem("app_language") as Language;
      if (savedLang === "vi" || savedLang === "en" || savedLang === "de") {
        return savedLang;
      }
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("app_language", lang);
    }
  };

  const t = (key: string): string => {
    return dictionary[language]?.[key] || dictionary["en"]?.[key] || dictionary["vi"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
