name: Fetch Logs
on:
  push:
    branches: [ "main" ]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch logs via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/quang18_5_2004/PronunCheck
            sudo journalctl -u pronuncheck-backend -n 200 --no-pager > backend_error_logs.txt
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add backend_error_logs.txt
            git commit -m "Fetch logs"
            git push origin main
